### PR TITLE
Opus support

### LINKED ISSUE #5: Can it support `opus` format?
It is happy to see an open-sourced library using my open-sourced library (https://github.com/fzyzcjy/flutter_rust_bridge) that seems useful to my app ;)

So, I wonder whether this package supports opus format? The doc is not yet very elaborate so I have not found information about this.

In addition, I wonder whether it is possible to support audio recording as well? (For example, opus format)

### PR DESCRIPTION
**Pull request by Yesterday17**
Basic support for opus format. Fixes #5

## Tested platforms
- [x] Windows (Build seems working)
- [x] Linux
- [x] macOS
  - [x] Intel
  - [x] ~~Apple Silicon~~ (I do not have a device, but the build seems working)
- [x] Android
- [x] iOS
  - [ ] Simulator: Playback becomes weird after switching to background
  - [x] iPadOS 16.2: Working well

## (Un)Resolved issues

- [x] ~~OPUS files can not loop.~~ Fixed in https://github.com/pdeljanov/Symphonia/pull/208. Cherry-picking might be necessary.
- [x] ~~Environment variable should be added on macOS: `export LIBOPUS_NO_PKG=1`~~ Not reproduced in CI 
- [x] **[Fixed in audiopus 0.3.0-rc.0]** Cross compiling on macOS seems broken. The arch seems wrong. The following error was produced:<details><pre><code>  = note: ld: warning: ignoring file /var/folders/rb/bxhfpzl102x2_tnj9yk973rw0000gq/T/rustcVhPrtK/libaudiopus_sys-3f9b1667c941e75f.rlib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
          Undefined symbols for architecture arm64:
            "_opus_decode_float", referenced from:
                _$LT$simple_audio..audio..opus..OpusDecoder$u20$as$u20$symphonia_core..codecs..Decoder$GT$::decode::h0b5a71e4cb0afd1a in simple_audio.simple_audio.c5df7263-cgu.15.rcgu.o
            "_opus_decoder_create", referenced from:
                core::ops::function::FnOnce::call_once::hd8bb0ff6e4953e9d in simple_audio.simple_audio.c5df7263-cgu.15.rcgu.o
            "_opus_decoder_ctl", referenced from:
                _$LT$simple_audio..audio..opus..OpusDecoder$u20$as$u20$symphonia_core..codecs..Decoder$GT$::reset::h473ffcfa89b67ec5 in simple_audio.simple_audio.c5df7263-cgu.15.rcgu.o
            "_opus_decoder_destroy", referenced from:
                core::ptr::drop_in_place$LT$audiopus..coder..decoder..Decoder$GT$::h2640be91522c9c00 in simple_audio.simple_audio.c5df7263-cgu.15.rcgu.o
                core::ptr::drop_in_place$LT$simple_audio..audio..opus..OpusDecoder$GT$::hb00d61fad74862dd in simple_audio.simple_audio.c5df7263-cgu.15.rcgu.o
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
</code></pre></details>
- [x] ~~Build fails on `x86_64-apple-ios` with:~~ Fixed in https://github.com/Lakelezz/audiopus_sys/pull/13 <details><pre><code>  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/limits.h:64:
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/machine/limits.h:11:2: error: architecture not supported
  #error architecture not supported</code></pre></details>

### CODE REVIEW

**Comment by erikas-taroza** [comment]
Hello @Yesterday17 

Thank you for your contribution. I will take a look at it later today.

**Comment by erikas-taroza** [comment]
Hello.

I tested on the `aarch64-linux-android` target and playback worked fine.

> OPUS files can not loop. Fixed in https://github.com/pdeljanov/Symphonia/pull/208. Cherry-picking might be necessary.

This can be cherry picked if it is not merged :)

**Comment by Yesterday17** [comment]
All CI has passed, marking as ready for review.

**Comment by erikas-taroza** [comment]
> All CI has passed, marking as ready for review.

Great! I will cherry pick the `symphonia` PR you linked above and review the changes.

File: rust/Cargo.toml [hunk 1]
```diff
@@ -14,15 +14,16 @@ reqwest = { version = "0", features = [
 	"rustls-tls",
 ], default-features = false }
 # symphonia = { version = "0.5.2", features = ["all"] }
-symphonia = { git = "https://github.com/erikas-taroza/Symphonia", branch = "mp4-improvements", features = [
-	"all",
-] }
+symphonia = { git = "https://github.com/erikas-taroza/Symphonia", branch = "mp4-improvements", features = ["all"] }
```
Comment (erikas-taroza) [inline rust/Cargo.toml:17]: Use the [`mp4-opus-improvements`](https://github.com/erikas-taroza/Symphonia/tree/mp4-opus-improvements) branch for Symphonia dependencies.

File: rust/src/audio/opus.rs [hunk 2]
```diff
@@ -0,0 +1,175 @@
...
+    errors::{decode_error, Result as SymphResult},
+    formats::Packet,
+};
+
+const SAMPLE_RATE: SampleRate = SampleRate::Hz48000;
+
+const SAMPLE_RATE_RAW: usize = 48_000;
+
+/// Number of audio frames/packets to be sent per second.
+const AUDIO_FRAME_RATE: usize = 1000 / 20; // FIXME: this value might be incorrect. We need to parse it from opus TOC.
```
Comment (erikas-taroza) [inline rust/src/audio/opus.rs:37]: Did you forget about this fixme?

**Review by erikas-taroza — CHANGES_REQUESTED** [review]

**Comment by Yesterday17** [comment]
You may also fork https://github.com/ProjectAnni/audiopus_sys and change the patch in `Cargo.toml` into your fork. :eyes:

**Comment by Yesterday17** [comment]
Update: Androi CI is shown as passing but actually failed. I'm investigating the reason.

**Comment by erikas-taroza** [comment]
Thanks for the changes!

> You may also fork https://github.com/ProjectAnni/audiopus_sys and change the patch in `Cargo.toml` into your fork. 👀

Good idea, will do that.

> Update: Androi CI is shown as passing but actually failed. I'm investigating the reason.

I need to fix that issue, caught me as well.

File: rust/Cargo.toml [hunk 3]
```diff
@@ -49,3 +50,6 @@ features = [
 
 [profile.release]
 lto = true
+
+[patch.crates-io]
+audiopus_sys = { git = "https://github.com/ProjectAnni/audiopus_sys" }
```
Comment (erikas-taroza) [inline rust/Cargo.toml:55]: Use this fork as discussed earlier: https://github.com/erikas-taroza/audiopus_sys

**Review by erikas-taroza — CHANGES_REQUESTED** [review]

**Comment by Yesterday17** [comment]
> I need to fix that issue, caught me as well.

I've resolved this issue in https://github.com/ProjectAnni/audiopus_sys/commit/80542b524ecee73bc352c843358519186951cf0a . It compiles on my machine. CI is still running to validate whether it works with GitHub Actions.

**Comment by erikas-taroza** [comment]
> > I need to fix that issue, caught me as well.
> 
> I've resolved this issue in [ProjectAnni/audiopus_sys@80542b5](https://github.com/ProjectAnni/audiopus_sys/commit/80542b524ecee73bc352c843358519186951cf0a) . It compiles on my machine. CI is still running to validate whether it works with GitHub Actions.

Looks like it worked :) I synced my fork with yours if you want to update the patch in `Cargo.toml`.

**Review by erikas-taroza — APPROVED** [review]
I appreciate the contribution :). LGTM
